### ISSUE TITLE
Domain name availability check returns unavailable for random domains

### ISSUE THREAD

**Issue by kryptocoin99** [B-DNS/Chrome#11]
Looks like domain name availability check isn't working. Returns "unavailable" for any random domain that is highly unlikely to be taken.

**Comment by astanze** [comment]
Like which name?

Does the same name again return "unavailable" (next hour or next day) or it's eventually checked correctly?

**Comment by astanze** [comment]
I have found the error and fixed it. If it still happens - reopen this issue.
