### ISSUE TITLE
Resolv issue

### ISSUE THREAD

**Issue by subnetsRU** [B-DNS/Chrome#3]
Hi.
Thanks for your work.
Not all domains are resolved. As example:
https://bdns.bz/r/nf.bit
https://bdns.bz/r/t411.bit
Reply is "nx" but I can say that it`s wrong, because for now I developing own DNS for chain.
Let test these names on my DNS:
```
# dig -t A nf.bit @dns.bitname.ru +short
94.23.252.190
# dig -t A t411.bit @dns.bitname.ru +short
ns-1714.awsdns-22.co.uk.
134.19.188.11
```

P.S. And can you add opennic project TLD`s ? (https://wiki.opennic.org/opennic/dot?redirect=1)

**Comment by astanze** [comment]
Thanks for your report.

>  https://bdns.bz/r/nf.bit

Namecoin doesn't seem to have any standard on the exact format for its records which currently contain all sort of stuff including plain text (emails, etc.). It's also unclear how IPs and subdomains are encoded when stored in JSON and what keys that JSON may have.

`nf.bit` had `ip` key but its `map` had no IPs which tripped my parser. Fixed.

>  https://bdns.bz/r/t411.bit

This one has only NSes. I haven't implemented DNS forwarding. Fixed.

> P.S. And can you add opennic project TLD`s ? (https://wiki.opennic.org/opennic/dot?redirect=1)

Done.

**Comment by subnetsRU** [comment]
>doesn't seem to have any standard on the exact format for its records 
Reed:
https://github.com/namecoin/proposals/blob/master/ifa-0001.md
https://wiki.namecoin.org/index.php?title=Domain_Name_Specification#Value_field

>Done.
Thanks.

**Comment by subnetsRU** [comment]
>Namecoin doesn't seem to have any standard on the exact format for its records

You can read:
https://wiki.namecoin.org/index.php?title=Domain_Name_Specification#Value_field
https://github.com/namecoin/proposals/blob/master/ifa-0001.md

>Done

Thanks.

**Comment by astanze** [comment]
> You can read:
https://wiki.namecoin.org/index.php?title=Domain_Name_Specification#Value_field
https://github.com/namecoin/proposals/blob/master/ifa-0001.md

In spite of what it's saying, current practice is seemingly random. For instance, there are domains without `ip` key that put their address under an empty key in `map` (even though the docs say `map` is meant for subdomains only), etc.

**Comment by subnetsRU** [comment]
And this is valid. The https://github.com/namecoin/proposals/blob/master/ifa-0001.md said:
The string "". The corresponding value is treated specially. All items inside the corresponding object are processed as though they are directly present inside the object containing the "map" item containing this key (the Immediate Ancestor), but only where the Immediate Ancestor does not have present any item with the same key. In other words, items which are present in the Immediate Ancestor take precedence over the items under the map item.

**Comment by astanze** [comment]
I admit I should have read it more attentively.

But I'm pretty sure these are still non-standard:

```
{
  "name": "x",
  "value": "{\"for_sale\" : 1, \"website\" : \"http://blockchained.com\", \"name\" : \"phelix\"}",
...
}
```

```
{
  "name": "bit",
  "value": "",
```
```
  {
    "name": "!",
    "value": "Contact Virtcoin@gmail.com if interested in purchasing.",
```

Yet there are quite a lot of them.

**Comment by subnetsRU** [comment]
True, these domain names are non-standard and we are not interested in them because they don`t have any IP`s.
I was talking about those domains that have IP in JSON value.

**Comment by astanze** [comment]
> True, these domain names are non-standard and we are not interested in them because they don't have any IPs.

For that part it's true. Currently my parser for Namecoin's value field is pretty dumb and doesn't follow the spec entirely so if you find more non-resolving domains please let me know.

I'm closing this issue since those particular problems were fixed. Feel free to reopen it or create a new one.
