### ISSUE TITLE
Would it be possible to state in update notice that why additional permission to read history is needed for updated addon version?

### ISSUE THREAD

**Issue by c933103** [B-DNS/Chrome#7]
Just asking.

**Comment by astanze** [comment]
> additional permission to read history 

Does the addon now require access to history? The only new permission added was `tabs`.

The reason why new permissions were requested is to let BDNS toolbar button indicate when you're on a B-TLD site or not (so if you are on a site like **nx.bit** the button will be grayed).

The commit with added permission is 82ac9d0cd74b9d910355f3d59ebb7cdf81b8bba6

There's not much code so you can see that no tracking or whatever has been added, if that's your concern.

**Comment by c933103** [comment]
humm strange there are no such permission in chrome extension page either, maybe I misread it initially
